#!/bin/sh
# Usage: bootscreen-subst "${MEDIA_TYPE}" "${DEBIAN_VERSION}" "${BUILD_DATE}"
#                          < file > outfile
sed -e "s/\${MEDIA_TYPE}/$1/" \
    -e "s/\${DEBIAN_VERSION}/$2/" \
    -e "s/\${BUILD_DATE}/$3/"
