#!/bin/sh -e

if [ ! -d pkg-lists ]; then
    echo "You must run this from the build directory"
    exit 1
fi

host=people.debian.org
basedir=public_html/d-i/images
dir=`date +%Y-%m-%d`

unset LANG LC_ALL LANGUAGE
cvs up || true

make reallyclean
for t in $(make all_list |grep '^build'); do
    (
    echo
    echo BUILDING IMAGE FOR $t
    echo
    fakeroot make $t
    ) 2>&1 | tee dest/$t.log # This is allowed to fail
done
fakeroot make all_stats | 2>&1 tee dest/stats.txt # This is allowed to fail

echo
echo UPLOADING FILES
echo

ssh $host mkdir -p $basedir/$dir/RSYNC_IN_PROGRESS
ssh $host cp -a $basedir/daily/. $basedir/$dir/RSYNC_IN_PROGRESS/ || true
rsync --stats -rv dest/ $host:$basedir/$dir/RSYNC_IN_PROGRESS/
ssh $host mv $basedir/$dir/RSYNC_IN_PROGRESS/\* $basedir/$dir/
ssh $host rmdir $basedir/$dir/RSYNC_IN_PROGRESS
ssh $host rm -f $basedir/daily
ssh $host ln -sf $dir $basedir/daily

make reallyclean
