#!/usr/bin/perl

$/="------------------------------------------------------------------------";

while (<>) {
	if (($m, $d)=/r\d+ \| ([^|]+) \| (\d+-\d+-\d+)/) {
		$d=~s/-\d+$//;
		if (/\.po/) {
			$pocount{$d}++;
		}
		$count{$d}++;
	}
}

my @list=sort keys %count;
pop @list; # remove last, probably incomplete month

foreach my $d (@list) {
	print "$d, $count{$d}, ".(defined $pocount{$d} ? $pocount{$d} : '0')."\n";
}
