#!/bin/sh

# This script is used for translations using .po files.
# It creates .xml files from the translated .po files.

if [ "$1" = "--help" ] ; then
    echo "Usage: $0 <language>"
    exit 0
fi

language=${1:-pl}

WORKDIR="./integrated"
SOURCEDIR="$WORKDIR/en"
PODIR="./po"
if [ -d "./$language/.svn" ] ; then
    LANGDIR="./$language.new"
else
    LANGDIR="./$language"
fi
RET=0

[ -d "$SOURCE" -o -d "$PODIR" ] || exit 1

[ -d "$LANGDIR" ] && rm -r $LANGDIR

echo "Creating .xml files for language '$language':"
for ORIGXML in `find $SOURCEDIR -name "*.xml"` ; do
    BASEDIR=$(dirname $ORIGXML | sed "s:$SOURCEDIR::" | sed "s:^/::")
    BASENAME=$(basename $ORIGXML .xml)
    PO=$PODIR/$BASEDIR/$BASENAME.$language.po
    XML=$LANGDIR/$BASEDIR/$BASENAME.xml
    DISP="$(echo $BASEDIR/$BASENAME | sed "s:^/::")"

    mkdir -p $LANGDIR/$BASEDIR

    if [ -f $PO ] ; then
        echo "- $DISP: creating translated .xml"
        po2xml $ORIGXML $PO > $XML
        RC=$?
        if [ $RC -ne 0 ] ; then
            RET=$RC
            echo "* $DISP: error $RC while executing po2xml"
        fi
    else
        echo "* $DISP: no .po file found; copying English original"
        cp $ORIGXML $LANGDIR/$BASEDIR
    fi
done

exit $RET
