#!/bin/sh

[ ! -d ./en/ ] && exit 1
[ ! -d ./po/ ] && mkdir po/

TARGET="./integrated"

cd $TARGET/

[ ! -d "./po/" ] && exit 1
for XML in `ls en/*.xml` ; do
    echo "Creating new .pot file for $XML"
    XML=$(basename $XML)
    POT=$(basename $XML .xml).pot
    xml2pot en/$XML >po/$DIR/$POT
done

exit 0
