#!/bin/sh
# This script is called at system startup
# This is where the installer actually interacts with the user

mount proc -t proc /proc

export DEBCONF_FRONTEND=text
#export DEBCONF_DEBUG=5 
/usr/bin/debconf-loadtemplate debian /var/lib/dpkg/info/*.templates 
/usr/share/debconf/frontend /usr/bin/main-menu


