Welcome to Debian GNU/Linux ${DEBIAN_VERSION}!

In addition to the default 'install' option, 
there is 'install-safe' which you should try if 
the system fails to boot at all (the typical
symptom is a white screen which doesn't go away).

For maximum control, you can use the'expert'
and 'expert-safe' options.

************************************
If in doubt, just choose 'install', and if that 
doesn't work, try 'install-safe'.
************************************
